version: '3'
services:
  app_service:
    image: node:11
    container_name: microservices
    build: .
    depends_on:
      - mongodb_container
    env_file:
      - .env
    environment:
      DB_HOST: localhost
    volumes:
      - .:/app
    ports:
      - 3000:3000
    working_dir: /app/
    network_mode: host
    command: /app/.docker/entrypoint.sh
    tty: true

  mongodb_container:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: